services:
  kafka1:
    image: apache/kafka:latest
    container_name: kafka1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CLUSTER_ID: "qtU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./kafka1_data:/var/lib/kafka/data

  kafka2:
    image: apache/kafka:latest
    container_name: kafka2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9094

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CLUSTER_ID: "qtU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "9094:9092"
      - "9095:9093"
    volumes:
      - ./kafka2_data:/var/lib/kafka/data

  kafka3:
    image: apache/kafka:latest
    container_name: kafka3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9096

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CLUSTER_ID: "qtU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "9096:9092"
      - "9097:9093"
    volumes:
      - ./kafka3_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka1
    ports:
      - "9002:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092
      DYNAMIC_CONFIG_ENABLED: true

networks:
  default:
    name: mod-id-net
    external: true

# 5L6g3nShT-eMCtK--X86sw
# c0bb734d-6fd3-4603-b88c-afba7b8078a9
#kafka-ui  | 2026-08-26 10:26:08,517 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka version: 3.5.0
#kafka-ui  | 2026-08-26 10:26:08,517 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka commitId: c97b88d5db4de28d
#kafka-ui  | 2026-08-26 10:26:08,517 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1787739968515
#kafka-ui  | 2026-08-26 10:26:08,552 INFO  [kafka-admin-client-thread | kafka-ui-admin-1787739968-1] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1787739968-1] Node -1 disconnected.
#kafka-ui  | 2026-08-26 10:26:08,555 WARN  [kafka-admin-client-thread | kafka-ui-admin-1787739968-1] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1787739968-1] Connection to node -1 (kafka1/10.89.0.7:29092) could not be established. Broker may not be available.
#kafka-ui  | 2026-08-26 10:26:08,658 INFO  [kafka-admin-client-thread | kafka-ui-admin-1787739968-1] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1787739968-1] Node -1 disconnected.
#kafka-ui  | 2026-08-26 10:26:08,659 WARN  [kafka-admin-client-thread | kafka-ui-admin-1787739968-1] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1787739968-1] Connection to node -1 (kafka1/10.89.0.7:29092) could not be established. Broker may not be available.
#    kafka1    | [2026-08-26 10:26:08,687] INFO [BrokerLifecycleManager id=1] Successfully registered broker 1 with broker epoch 1359 (org.apache.kafka.server.BrokerLifecycleManager)
#    kafka1    | [2026-08-26 10:26:08,706] INFO [BrokerLifecycleManager id=1] The broker has caught up. Transitioning from STARTING to RECOVERY. (org.apache.kafka.server.BrokerLifecycleManager)
#    kafka1    | [2026-08-26 10:26:08,706] INFO [BrokerServer id=1] Finished waiting for the controller to acknowledge that we are caught up (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,706] INFO [BrokerServer id=1] Waiting for the initial broker metadata update to be published (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,706] INFO [BrokerServer id=1] Finished waiting for the initial broker metadata update to be published (kafka.server.BrokerServer)
#kafka1    | [2026-08-26 10:26:08,708] INFO KafkaConfig values:
#    kafka1    |     add.partitions.to.txn.retry.backoff.max.ms = 100
#    kafka1    |     add.partitions.to.txn.retry.backoff.ms = 20
#    kafka1    |     advertised.listeners = [INTERNAL://kafka1:29092, EXTERNAL://localhost:9092]
#    kafka1    |     alter.config.policy.class.name = null
#    kafka1    |     alter.log.dirs.replication.quota.window.num = 11
#    kafka1    |     alter.log.dirs.replication.quota.window.size.seconds = 1
#    kafka1    |     authorizer.class.name =
#    kafka1    |     auto.create.topics.enable = true
#    kafka1    |     auto.leader.rebalance.enable = true
#    kafka1    |     background.threads = 10
#    kafka1    |     broker.heartbeat.interval.ms = 2000
#    kafka1    |     broker.id = 1
#    kafka1    |     broker.rack = null
#    kafka1    |     broker.session.timeout.ms = 9000
#    kafka1    |     client.quota.callback.class = null
#    kafka1    |     compression.gzip.level = -1
#    kafka1    |     compression.lz4.level = 9
#    kafka1    |     compression.type = producer
#    kafka1    |     compression.zstd.level = 3
#    kafka1    |     config.providers = []
#    kafka1    |     connection.failed.authentication.delay.ms = 100
#    kafka1    |     connections.max.idle.ms = 600000
#    kafka1    |     connections.max.reauth.ms = 0
#    kafka1    |     controlled.shutdown.enable = true
#    kafka1    |     controller.listener.names = [CONTROLLER]
#    kafka1    |     controller.performance.always.log.threshold.ms = 2000
#    kafka1    |     controller.performance.sample.period.ms = 60000
#    kafka1    |     controller.quorum.append.linger.ms = 25
#    kafka1    |     controller.quorum.auto.join.enable = false
#    kafka1    |     controller.quorum.bootstrap.servers = []
#    kafka1    |     controller.quorum.election.backoff.max.ms = 1000
#    kafka1    |     controller.quorum.election.timeout.ms = 1000
#    kafka1    |     controller.quorum.fetch.max.bytes = 1048576
#    kafka1    |     controller.quorum.fetch.snapshot.max.bytes = 1048576
#    kafka1    |     controller.quorum.fetch.timeout.ms = 2000
#    kafka1    |     controller.quorum.request.timeout.ms = 2000
#    kafka1    |     controller.quorum.retry.backoff.ms = 20
#    kafka1    |     controller.quorum.voters = [1@kafka1:9093, 2@kafka2:9093, 3@kafka3:9093]
#    kafka1    |     controller.quota.window.num = 11
#    kafka1    |     controller.quota.window.size.seconds = 1
#    kafka1    |     controller.socket.timeout.ms = 30000
#    kafka1    |     cordoned.log.dirs = []
#    kafka1    |     create.topic.policy.class.name = null
#    kafka1    |     default.replication.factor = 1
#    kafka1    |     delegation.token.expiry.check.interval.ms = 3600000
#    kafka1    |     delegation.token.expiry.time.ms = 86400000
#    kafka1    |     delegation.token.max.lifetime.ms = 604800000
#    kafka1    |     delegation.token.secret.key = null
#    kafka1    |     delete.records.purgatory.purge.interval.requests = 1
#    kafka1    |     delete.topic.enable = true
#    kafka1    |     early.start.listeners = null
#    kafka1    |     fetch.max.bytes = 57671680
#    kafka1    |     fetch.purgatory.purge.interval.requests = 1000
#    kafka1    |     follower.fetch.last.tiered.offset.enable = false
#    kafka1    |     group.consumer.assignment.interval.ms = 1000
#    kafka1    |     group.consumer.assignors = [uniform, range]
#    kafka1    |     group.consumer.heartbeat.interval.ms = 5000
#    kafka1    |     group.consumer.max.assignment.interval.ms = 15000
#    kafka1    |     group.consumer.max.heartbeat.interval.ms = 15000
#    kafka1    |     group.consumer.max.session.timeout.ms = 60000
#    kafka1    |     group.consumer.max.size = 2147483647
#    kafka1    |     group.consumer.migration.policy = bidirectional
#    kafka1    |     group.consumer.min.assignment.interval.ms = 0
#    kafka1    |     group.consumer.min.heartbeat.interval.ms = 5000
#    kafka1    |     group.consumer.min.session.timeout.ms = 45000
#    kafka1    |     group.consumer.regex.refresh.interval.ms = 600000
#    kafka1    |     group.consumer.session.timeout.ms = 45000
#    kafka1    |     group.coordinator.append.linger.ms = -1
#    kafka1    |     group.coordinator.background.threads = 2
#    kafka1    |     group.coordinator.cached.buffer.max.bytes = 1048588
#    kafka1    |     group.coordinator.rebalance.protocols = [classic, consumer, streams]
#    kafka1    |     group.coordinator.threads = 4
#    kafka1    |     group.initial.rebalance.delay.ms = 0
#    kafka1    |     group.max.session.timeout.ms = 1800000
#    kafka1    |     group.max.size = 2147483647
#    kafka1    |     group.min.session.timeout.ms = 6000
#    kafka1    |     group.share.assignment.interval.ms = 1000
#    kafka1    |     group.share.assignors = [simple]
#    kafka1    |     group.share.delivery.count.limit = 5
#    kafka1    |     group.share.heartbeat.interval.ms = 5000
#    kafka1    |     group.share.initialize.retry.interval.ms = 30000
#    kafka1    |     group.share.max.assignment.interval.ms = 15000
#    kafka1    |     group.share.max.delivery.count.limit = 10
#    kafka1    |     group.share.max.heartbeat.interval.ms = 15000
#    kafka1    |     group.share.max.partition.max.record.locks = 4000
#    kafka1    |     group.share.max.record.lock.duration.ms = 60000
#    kafka1    |     group.share.max.session.timeout.ms = 60000
#    kafka1    |     group.share.max.share.sessions = 2000
#    kafka1    |     group.share.max.size = 200
#    kafka1    |     group.share.min.assignment.interval.ms = 0
#    kafka1    |     group.share.min.delivery.count.limit = 2
#    kafka1    |     group.share.min.heartbeat.interval.ms = 5000
#    kafka1    |     group.share.min.partition.max.record.locks = 100
#    kafka1    |     group.share.min.record.lock.duration.ms = 15000
#    kafka1    |     group.share.min.session.timeout.ms = 45000
#    kafka1    |     group.share.partition.max.record.locks = 2000
#    kafka1    |     group.share.persister.class.name = org.apache.kafka.server.share.persister.DefaultStatePersister
#    kafka1    |     group.share.record.lock.duration.ms = 30000
#    kafka1    |     group.share.session.timeout.ms = 45000
#    kafka1    |     group.streams.assignment.interval.ms = 1000
#    kafka1    |     group.streams.heartbeat.interval.ms = 5000
#    kafka1    |     group.streams.initial.rebalance.delay.ms = 3000
#    kafka1    |     group.streams.max.assignment.interval.ms = 15000
#    kafka1    |     group.streams.max.heartbeat.interval.ms = 15000
#    kafka1    |     group.streams.max.session.timeout.ms = 60000
#    kafka1    |     group.streams.max.size = 2147483647
#    kafka1    |     group.streams.max.standby.replicas = 2
#    kafka1    |     group.streams.min.assignment.interval.ms = 0
#    kafka1    |     group.streams.min.heartbeat.interval.ms = 5000
#    kafka1    |     group.streams.min.session.timeout.ms = 45000
#    kafka1    |     group.streams.num.standby.replicas = 0
#    kafka1    |     group.streams.session.timeout.ms = 45000
#    kafka1    |     initial.broker.registration.timeout.ms = 60000
#    kafka1    |     inter.broker.listener.name = INTERNAL
#    kafka1    |     internal.metadata.delete.delay.millis = 60000
#    kafka1    |     internal.metadata.log.segment.bytes = null
#    kafka1    |     internal.metadata.max.batch.size.in.bytes = 8388608
#    kafka1    |     kafka.metrics.polling.interval.secs = 10
#    kafka1    |     kafka.metrics.reporters = []
#    kafka1    |     leader.imbalance.check.interval.seconds = 300
#    kafka1    |     listener.security.protocol.map = CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#    kafka1    |     listeners = [INTERNAL://:29092, EXTERNAL://:9092, CONTROLLER://:9093]
#    kafka1    |     log.cleaner.backoff.ms = 15000
#    kafka1    |     log.cleaner.dedupe.buffer.size = 134217728
#    kafka1    |     log.cleaner.delete.retention.ms = 86400000
#    kafka1    |     log.cleaner.enable = true
#    kafka1    |     log.cleaner.io.buffer.load.factor = 0.9
#    kafka1    |     log.cleaner.io.buffer.size = 524288
#    kafka1    |     log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
#    kafka1    |     log.cleaner.max.compaction.lag.ms = 9223372036854775807
#    kafka1    |     log.cleaner.min.cleanable.ratio = 0.5
#    kafka1    |     log.cleaner.min.compaction.lag.ms = 0
#    kafka1    |     log.cleaner.threads = 1
#    kafka1    |     log.cleanup.policy = [delete]
#    kafka1    |     log.dir = [/tmp/kafka-logs]
#    kafka1    |     log.dir.failure.timeout.ms = 30000
#    kafka1    |     log.dirs = null
#    kafka1    |     log.flush.interval.messages = 9223372036854775807
#    kafka1    |     log.flush.interval.ms = null
#    kafka1    |     log.flush.offset.checkpoint.interval.ms = 60000
#    kafka1    |     log.flush.scheduler.interval.ms = 9223372036854775807
#    kafka1    |     log.flush.start.offset.checkpoint.interval.ms = 60000
#    kafka1    |     log.index.interval.bytes = 4096
#    kafka1    |     log.index.size.max.bytes = 10485760
#    kafka1    |     log.initial.task.delay.ms = 30000
#    kafka1    |     log.local.retention.bytes = -2
#    kafka1    |     log.local.retention.ms = -2
#    kafka1    |     log.message.timestamp.after.max.ms = 3600000
#    kafka1    |     log.message.timestamp.before.max.ms = 9223372036854775807
#    kafka1    |     log.message.timestamp.type = CreateTime
#    kafka1    |     log.preallocate = false
#    kafka1    |     log.retention.bytes = -1
#    kafka1    |     log.retention.check.interval.ms = 300000
#    kafka1    |     log.retention.hours = 168
#    kafka1    |     log.retention.minutes = null
#    kafka1    |     log.retention.ms = null
#    kafka1    |     log.roll.hours = 168
#    kafka1    |     log.roll.jitter.hours = 0
#    kafka1    |     log.roll.jitter.ms = null
#    kafka1    |     log.roll.ms = null
#    kafka1    |     log.segment.bytes = 1073741824
#    kafka1    |     log.segment.delete.delay.ms = 60000
#    kafka1    |     max.connection.creation.rate = 2147483647
#    kafka1    |     max.connections = 2147483647
#    kafka1    |     max.connections.per.ip = 2147483647
#    kafka1    |     max.connections.per.ip.overrides =
#    kafka1    |     max.incremental.fetch.session.cache.slots = 1000
#    kafka1    |     max.request.partition.size.limit = 2000
#    kafka1    |     message.max.bytes = 1048588
#    kafka1    |     metadata.log.dir = null
#    kafka1    |     metadata.log.max.record.bytes.between.snapshots = 20971520
#    kafka1    |     metadata.log.max.snapshot.interval.ms = 3600000
#    kafka1    |     metadata.log.segment.bytes = 1073741824
#    kafka1    |     metadata.log.segment.ms = 604800000
#    kafka1    |     metadata.max.idle.interval.ms = 500
#    kafka1    |     metadata.max.retention.bytes = 104857600
#    kafka1    |     metadata.max.retention.ms = 604800000
#    kafka1    |     metric.reporters = [org.apache.kafka.common.metrics.JmxReporter]
#    kafka1    |     metrics.num.samples = 2
#    kafka1    |     metrics.recording.level = INFO
#    kafka1    |     metrics.sample.window.ms = 30000
#    kafka1    |     min.insync.replicas = 1
#    kafka1    |     node.id = 1
#    kafka1    |     num.io.threads = 8
#    kafka1    |     num.network.threads = 3
#    kafka1    |     num.partitions = 1
#    kafka1    |     num.recovery.threads.per.data.dir = 2
#    kafka1    |     num.replica.alter.log.dirs.threads = null
#    kafka1    |     num.replica.fetchers = 1
#    kafka1    |     offset.metadata.max.bytes = 4096
#    kafka1    |     offsets.commit.timeout.ms = 5000
#    kafka1    |     offsets.load.buffer.size = 5242880
#    kafka1    |     offsets.retention.check.interval.ms = 600000
#    kafka1    |     offsets.retention.minutes = 10080
#    kafka1    |     offsets.topic.compression.codec = 0
#    kafka1    |     offsets.topic.num.partitions = 50
#    kafka1    |     offsets.topic.replication.factor = 3
#    kafka1    |     offsets.topic.segment.bytes = 104857600
#    kafka1    |     principal.builder.class = class org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder
#    kafka1    |     process.roles = [broker, controller]
#    kafka1    |     producer.id.expiration.check.interval.ms = 600000
#    kafka1    |     producer.id.expiration.ms = 86400000
#    kafka1    |     producer.purgatory.purge.interval.requests = 1000
#    kafka1    |     queued.max.request.bytes = -1
#    kafka1    |     queued.max.requests = 500
#    kafka1    |     quota.window.num = 11
#    kafka1    |     quota.window.size.seconds = 1
#    kafka1    |     remote.fetch.max.wait.ms = 500
#    kafka1    |     remote.list.offsets.request.timeout.ms = 30000
#    kafka1    |     remote.log.index.file.cache.total.size.bytes = 1073741824
#    kafka1    |     remote.log.index.file.cache.ttl.ms = 900000
#    kafka1    |     remote.log.manager.copier.thread.pool.size = 10
#    kafka1    |     remote.log.manager.copy.max.bytes.per.second = 9223372036854775807
#    kafka1    |     remote.log.manager.copy.quota.window.num = 11
#    kafka1    |     remote.log.manager.copy.quota.window.size.seconds = 1
#    kafka1    |     remote.log.manager.expiration.thread.pool.size = 10
#    kafka1    |     remote.log.manager.fetch.max.bytes.per.second = 9223372036854775807
#    kafka1    |     remote.log.manager.fetch.quota.window.num = 11
#    kafka1    |     remote.log.manager.fetch.quota.window.size.seconds = 1
#    kafka1    |     remote.log.manager.follower.thread.pool.size = 2
#    kafka1    |     remote.log.manager.task.interval.ms = 30000
#    kafka1    |     remote.log.manager.task.retry.backoff.max.ms = 30000
#    kafka1    |     remote.log.manager.task.retry.backoff.ms = 500
#    kafka1    |     remote.log.manager.task.retry.jitter = 0.2
#    kafka1    |     remote.log.manager.thread.pool.size = 2
#    kafka1    |     remote.log.metadata.custom.metadata.max.bytes = 128
#    kafka1    |     remote.log.metadata.manager.class.name = org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager
#    kafka1    |     remote.log.metadata.manager.class.path = null
#    kafka1    |     remote.log.metadata.manager.impl.prefix = rlmm.config.
#    kafka1    |     remote.log.metadata.manager.listener.name = null
#    kafka1    |     remote.log.reader.max.pending.tasks = 100
#    kafka1    |     remote.log.reader.threads = 10
#    kafka1    |     remote.log.storage.manager.class.name = null
#    kafka1    |     remote.log.storage.manager.class.path = null
#    kafka1    |     remote.log.storage.manager.impl.prefix = rsm.config.
#    kafka1    |     remote.log.storage.system.enable = false
#    kafka1    |     replica.fetch.backoff.ms = 1000
#    kafka1    |     replica.fetch.max.bytes = 1048576
#    kafka1    |     replica.fetch.min.bytes = 1
#    kafka1    |     replica.fetch.response.max.bytes = 10485760
#    kafka1    |     replica.fetch.wait.max.ms = 500
#    kafka1    |     replica.high.watermark.checkpoint.interval.ms = 5000
#    kafka1    |     replica.lag.time.max.ms = 30000
#    kafka1    |     replica.selector.class = null
#    kafka1    |     replica.socket.receive.buffer.bytes = 65536
#    kafka1    |     replica.socket.timeout.ms = 30000
#    kafka1    |     replication.quota.window.num = 11
#    kafka1    |     replication.quota.window.size.seconds = 1
#    kafka1    |     request.timeout.ms = 30000
#    kafka1    |     sasl.client.callback.handler.class = null
#    kafka1    |     sasl.enabled.mechanisms = [GSSAPI]
#    kafka1    |     sasl.jaas.config = null
#    kafka1    |     sasl.kerberos.kinit.cmd = /usr/bin/kinit
#    kafka1    |     sasl.kerberos.min.time.before.relogin = 60000
#    kafka1    |     sasl.kerberos.principal.to.local.rules = [DEFAULT]
#    kafka1    |     sasl.kerberos.service.name = null
#    kafka1    |     sasl.kerberos.ticket.renew.jitter = 0.05
#    kafka1    |     sasl.kerberos.ticket.renew.window.factor = 0.8
#    kafka1    |     sasl.login.callback.handler.class = null
#    kafka1    |     sasl.login.class = null
#    kafka1    |     sasl.login.connect.timeout.ms = null
#    kafka1    |     sasl.login.read.timeout.ms = null
#    kafka1    |     sasl.login.refresh.buffer.seconds = 300
#    kafka1    |     sasl.login.refresh.min.period.seconds = 60
#    kafka1    |     sasl.login.refresh.window.factor = 0.8
#    kafka1    |     sasl.login.refresh.window.jitter = 0.05
#    kafka1    |     sasl.login.retry.backoff.max.ms = 10000
#    kafka1    |     sasl.login.retry.backoff.ms = 100
#    kafka1    |     sasl.mechanism.controller.protocol = GSSAPI
#    kafka1    |     sasl.mechanism.inter.broker.protocol = GSSAPI
#    kafka1    |     sasl.oauthbearer.assertion.algorithm = RS256
#    kafka1    |     sasl.oauthbearer.assertion.claim.aud = null
#    kafka1    |     sasl.oauthbearer.assertion.claim.exp.seconds = 300
#    kafka1    |     sasl.oauthbearer.assertion.claim.iss = null
#    kafka1    |     sasl.oauthbearer.assertion.claim.jti.include = false
#    kafka1    |     sasl.oauthbearer.assertion.claim.nbf.seconds = 60
#    kafka1    |     sasl.oauthbearer.assertion.claim.sub = null
#    kafka1    |     sasl.oauthbearer.assertion.file = null
#    kafka1    |     sasl.oauthbearer.assertion.private.key.file = null
#    kafka1    |     sasl.oauthbearer.assertion.private.key.passphrase = null
#    kafka1    |     sasl.oauthbearer.assertion.template.file = null
#    kafka1    |     sasl.oauthbearer.client.credentials.client.id = null
#    kafka1    |     sasl.oauthbearer.client.credentials.client.secret = null
#    kafka1    |     sasl.oauthbearer.clock.skew.seconds = 30
#    kafka1    |     sasl.oauthbearer.expected.audience = []
#    kafka1    |     sasl.oauthbearer.expected.issuer = null
#    kafka1    |     sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
#    kafka1    |     sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
#    kafka1    |     sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
#    kafka1    |     sasl.oauthbearer.jwks.endpoint.url = null
#    kafka1    |     sasl.oauthbearer.jwt.retriever.class = class org.apache.kafka.common.security.oauthbearer.DefaultJwtRetriever
#    kafka1    |     sasl.oauthbearer.jwt.validator.class = class org.apache.kafka.common.security.oauthbearer.DefaultJwtValidator
#    kafka1    |     sasl.oauthbearer.scope = null
#    kafka1    |     sasl.oauthbearer.scope.claim.name = scope
#    kafka1    |     sasl.oauthbearer.sub.claim.name = sub
#    kafka1    |     sasl.oauthbearer.token.endpoint.url = null
#    kafka1    |     sasl.server.callback.handler.class = null
#    kafka1    |     sasl.server.max.receive.size = 524288
#    kafka1    |     security.inter.broker.protocol = PLAINTEXT
#    kafka1    |     security.providers = null
#    kafka1    |     server.max.startup.time.ms = 9223372036854775807
#    kafka1    |     share.coordinator.append.linger.ms = -1
#    kafka1    |     share.coordinator.cached.buffer.max.bytes = 1048588
#    kafka1    |     share.coordinator.cold.partition.snapshot.interval.ms = 300000
#    kafka1    |     share.coordinator.load.buffer.size = 5242880
#    kafka1    |     share.coordinator.snapshot.update.records.per.snapshot = 500
#    kafka1    |     share.coordinator.state.topic.compression.codec = 0
#    kafka1    |     share.coordinator.state.topic.min.isr = 2
#    kafka1    |     share.coordinator.state.topic.num.partitions = 50
#    kafka1    |     share.coordinator.state.topic.prune.interval.ms = 300000
#    kafka1    |     share.coordinator.state.topic.replication.factor = 3
#    kafka1    |     share.coordinator.state.topic.segment.bytes = 104857600
#    kafka1    |     share.coordinator.threads = 1
#    kafka1    |     share.coordinator.write.timeout.ms = 5000
#    kafka1    |     share.fetch.purgatory.purge.interval.requests = 1000
#    kafka1    |     socket.connection.setup.timeout.max.ms = 30000
#    kafka1    |     socket.connection.setup.timeout.ms = 10000
#    kafka1    |     socket.listen.backlog.size = 50
#    kafka1    |     socket.receive.buffer.bytes = 102400
#    kafka1    |     socket.request.max.bytes = 104857600
#    kafka1    |     socket.send.buffer.bytes = 102400
#    kafka1    |     ssl.allow.dn.changes = false
#    kafka1    |     ssl.allow.san.changes = false
#    kafka1    |     ssl.cipher.suites = []
#    kafka1    |     ssl.client.auth = none
#    kafka1    |     ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
#    kafka1    |     ssl.endpoint.identification.algorithm = https
#    kafka1    |     ssl.engine.factory.class = null
#    kafka1    |     ssl.key.password = null
#    kafka1    |     ssl.keymanager.algorithm = SunX509
#    kafka1    |     ssl.keystore.certificate.chain = null
#    kafka1    |     ssl.keystore.key = null
#    kafka1    |     ssl.keystore.location = null
#    kafka1    |     ssl.keystore.password = null
#    kafka1    |     ssl.keystore.type = JKS
#    kafka1    |     ssl.principal.mapping.rules = DEFAULT
#    kafka1    |     ssl.protocol = TLSv1.3
#    kafka1    |     ssl.provider = null
#    kafka1    |     ssl.secure.random.implementation = null
#    kafka1    |     ssl.trustmanager.algorithm = PKIX
#    kafka1    |     ssl.truststore.certificates = null
#    kafka1    |     ssl.truststore.location = null
#    kafka1    |     ssl.truststore.password = null
#    kafka1    |     ssl.truststore.type = JKS
#    kafka1    |     telemetry.max.bytes = 1048576
#    kafka1    |     transaction.abort.timed.out.transaction.cleanup.interval.ms = 10000
#    kafka1    |     transaction.max.timeout.ms = 900000
#    kafka1    |     transaction.partition.verification.enable = true
#    kafka1    |     transaction.remove.expired.transaction.cleanup.interval.ms = 3600000
#    kafka1    |     transaction.state.log.load.buffer.size = 5242880
#    kafka1    |     transaction.state.log.min.isr = 2
#    kafka1    |     transaction.state.log.num.partitions = 50
#    kafka1    |     transaction.state.log.replication.factor = 3
#    kafka1    |     transaction.state.log.segment.bytes = 104857600
#    kafka1    |     transaction.two.phase.commit.enable = false
#    kafka1    |     transactional.id.expiration.ms = 604800000
#    kafka1    |     unclean.leader.election.enable = false
#    kafka1    |     unclean.leader.election.interval.ms = 300000
#    kafka1    |     unstable.api.versions.enable = false
#    kafka1    |     unstable.feature.versions.enable = false
#    kafka1    |  (org.apache.kafka.common.config.AbstractConfig)
#    kafka1    | [2026-08-26 10:26:08,713] INFO [BrokerServer id=1] Waiting for the broker to be unfenced (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,763] INFO [BrokerLifecycleManager id=1] The broker has been unfenced. Transitioning from RECOVERY to RUNNING. (org.apache.kafka.server.BrokerLifecycleManager)
#    kafka1    | [2026-08-26 10:26:08,764] INFO [BrokerServer id=1] Finished waiting for the broker to be unfenced (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,766] INFO authorizerStart completed for endpoint INTERNAL. Endpoint is now READY. (org.apache.kafka.server.network.EndpointReadyFutures)
#    kafka1    | [2026-08-26 10:26:08,767] INFO authorizerStart completed for endpoint EXTERNAL. Endpoint is now READY. (org.apache.kafka.server.network.EndpointReadyFutures)
#    kafka1    | [2026-08-26 10:26:08,767] INFO [SocketServer listenerType=BROKER, nodeId=1] Enabling request processing. (kafka.network.SocketServer)
#    kafka1    | [2026-08-26 10:26:08,768] INFO Awaiting socket connections on 0.0.0.0:29092. (kafka.network.DataPlaneAcceptor)
#    kafka1    | [2026-08-26 10:26:08,773] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.DataPlaneAcceptor)
#    kafka1    | [2026-08-26 10:26:08,785] INFO [BrokerServer id=1] Waiting for all of the authorizer futures to be completed (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,786] INFO [BrokerServer id=1] Finished waiting for all of the authorizer futures to be completed (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,787] INFO [BrokerServer id=1] Waiting for all of the SocketServer Acceptors to be started (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,787] INFO [BrokerServer id=1] Finished waiting for all of the SocketServer Acceptors to be started (kafka.server.BrokerServer)
#    kafka1    | [2026-08-26 10:26:08,788] INFO [BrokerServer id=1] Transition from STARTING to STARTED (kafka.server.BrokerServer)
#kafka1    | [2026-08-26 10:26:08,789] INFO Kafka version: 4.3.1 (org.apache.kafka.common.utils.AppInfoParser)
#kafka1    | [2026-08-26 10:26:08,790] INFO Kafka commitId: 26b251a451ce941d (org.apache.kafka.common.utils.AppInfoParser)
#kafka1    | [2026-08-26 10:26:08,790] INFO Kafka startTimeMs: 1787739968789 (org.apache.kafka.common.utils.AppInfoParser)
#    kafka1    | [2026-08-26 10:26:08,794] INFO [KafkaRaftServer nodeId=1] Kafka Server started (kafka.server.KafkaRaftServer)
#kafka-ui  | 2026-08-26 10:26:09,549 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
#kafka-ui  | 2026-08-26 10:26:36,729 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
#kafka-ui  | 2026-08-26 10:26:36,741 DEBUG [parallel-4] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
#kafka-ui  | 2026-08-26 10:27:06,729 DEBUG [parallel-5] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
#kafka-ui  | 2026-08-26 10:27:06,748 DEBUG [parallel-8] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
#kafka-ui  | 2026-08-26 10:27:36,729 DEBUG [parallel-6] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
#kafka-ui  | 2026-08-26 10:27:36,739 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
#kafka-ui  | 2026-08-26 10:28:06,729 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
#kafka-ui  | 2026-08-26 10:28:06,737 DEBUG [parallel-5] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
#kafka-ui  | 2026-08-26 10:28:36,729 DEBUG [parallel-6] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
#kafka-ui  | 2026-08-26 10:28:36,740 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
